import 'language_controller.dart';

class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      // Core Navigation & Tabs
      'app_title': 'SplitLedger',
      'home_tab': 'Home',
      'split_tab': 'Split',
      'history_tab': 'Ledger',
      'reports_tab': 'Reports',
      'settings_tab': 'Settings',

      // Dashboard Header & Cards
      'wallet': 'Wallet',
      'set_wallet': 'Set Wallet Amount',
      'wallet_amount': 'Wallet Amount',
      'wallet_balance': 'Your Wallet Balance',
      'wallet_desc': 'Enter total budget or cash in hand:',
      'wallet_not_set': 'Tap to set initial amount',
      'total_received': 'Total Received',
      'total_paid': 'Total Paid',
      'your_balance': 'Your Balance',
      'cash_in': 'Cash In',
      'cash_out': 'Cash Out',
      'you_paid': 'You Paid',
      'you_received': 'You Received',
      'quick_expense': '1-Tap Quick',
      'quick_save_expense': '⚡ Quick Save Expense',
      'spend_cash_out': 'Spend (Cash Out)',
      'receive_cash_in': 'Receive (Cash In)',
      'settle_up': 'Settle Up',
      'settlements': 'Settlements & Dues',
      'no_due': 'All Settled Up! 🎉',
      'no_due_sub': 'No pending dues in this group.',
      'dues_pending': 'dues pending',
      'pay_upi': 'UPI Pay',
      'remind_whatsapp': 'WhatsApp',
      'mark_paid': 'Mark as Paid',

      // Daily Budget & Targets
      'daily_spend_target': 'Daily Spend Target',
      'safe_spend_per_day': 'per day safe spend',
      'days_left_in': 'days left in',
      'over_budget': 'Over budget for this month',
      'tight_budget': 'Tight Budget: Spend carefully',
      'on_track': 'On Track: Healthy budget',
      'set_wallet_target': 'Set Wallet to calculate daily budget',

      // Category Breakdown & Reports
      'category_breakdown': 'Category Breakdown',
      'category_spending_breakdown': 'Category Spending Breakdown',
      'total_group_expense': 'Total Group Expense',
      'spending_by_member': 'Spending by Member',
      'member_contributions': 'Member Contributions',

      // Time Filters
      'all_time': 'All Time',
      'monthly': 'Monthly',
      'daily': 'Daily',
      'weekly': 'Weekly',
      'yearly': 'Yearly',
      'pick_month': 'Pick Month',

      // Search, Filter & Export
      'search_hint': 'Search notes, category, or name...',
      'search_title': 'Search Transactions',
      'filter_options': 'Options',
      'select_date_range': 'Select Date Range',
      'filter_by_amount': 'Filter by Amount',
      'min_amount': 'Min Amount (₹)',
      'max_amount': 'Max Amount (₹)',
      'apply_filter': 'Apply Filter',
      'clear_filter': 'Clear',
      'export_csv': 'Export CSV / Excel',
      'export_pdf': 'Export PDF',
      'share_app': 'Share App',

      // Settings & Appearance
      'appearance_theme': 'Appearance & Theme',
      'theme_accent_color': 'Theme Accent Color',
      'theme_mode_system': 'System',
      'theme_mode_light': 'Light',
      'theme_mode_dark': 'Dark',
      'language': 'Language / மொழி',
      'household_settings': 'Household Settings',
      'household_name': 'Household Name',
      'invite_code': 'Your Invite Code',
      'invite_code_copied': 'Invite code copied to clipboard!',
      'help_support': 'Help & Support',
      'privacy_mode': 'Privacy Mode (Hide Balances)',
      'privacy_mode_sub': 'Mask sensitive balance numbers on cards with dots',
      'storage_backup_title': 'Data Storage & Backup',
      'storage_mode': 'Storage Mode',
      'storage_cloud': 'Cloud Sync (Firebase)',
      'storage_local': 'Device Only (Offline)',
      'storage_mode_desc': 'Switch between real-time cloud sync and private offline local storage.',
      'backup_export': 'Backup Data (JSON)',
      'backup_export_sub': 'Download or share all transactions and balances',
      'restore_import': 'Restore Data (JSON)',
      'restore_import_sub': 'Import transactions from a JSON backup file or text',
      'logout': 'Logout',
      'logout_confirm': 'Are you sure you want to logout?',
      'leave_household': 'Leave Household',
      'leave_household_confirm': 'Are you sure you want to leave this household? You will lose access to group data.',
      'clear_all_tx': 'Clear All Transactions',
      'clear_all_tx_confirm': 'Are you sure you want to delete ALL transactions in this household? This cannot be undone.',

      // Categories
      'currency': 'Currency',
      'food': 'Food & Dining',
      'fuel': 'Fuel & Travel',
      'tea': 'Tea & Snacks',
      'grocery': 'Groceries',
      'rent': 'Rent & House',
      'bills': 'Utilities & Bills',
      'entertainment': 'Fun & Movies',
      'shopping': 'Shopping',
      'medical': 'Medical & Health',
      'settle': 'Settlement',
      'other': 'Others',

      // Actions & Dialogs
      'cancel': 'Cancel',
      'save': 'Save',
      'update': 'Update',
      'delete': 'Delete',
      'edit': 'Edit',
      'close': 'Close',
      'done': 'Done',
      'copy': 'Copy',
      'paste_clipboard': 'Paste from Clipboard',
      'replace_existing': 'Replace existing transactions',
      'replace_existing_sub': 'If checked, current transactions will be cleared first',
      'restore_now': 'Restore Now',
      'delete_tx_title': 'Delete Transaction?',
      'delete_tx_confirm': 'Are you sure you want to delete this transaction?',
      'tx_deleted': 'Transaction deleted',

      // Table & List Headers
      'recent_transactions': 'Recent Transactions',
      'no_transactions_yet': 'No transactions yet.',
      'tap_to_add_tx': 'Tap + to add your first expense or split',
      'no_matching_tx': 'No matching transactions found.',
      'notes_category_header': 'Notes / Category',
      'amount_header': 'Amount',
      'by_header': 'Paid By',
      'you': 'You',
      'description': 'Description',
      'category': 'Category',
      'date_time': 'Date & Time',
      'due_date': 'Due Date',
      'repeat': 'Repeat',
      'end_date_optional': 'End Date (optional)',

      // Add & Edit Transaction
      'add_transaction': 'Add Transaction',
      'edit_transaction': 'Edit Transaction',
      'who_paid': 'Who Paid?',
      'who_received': 'Who Received?',
      'amount_paid': 'Amount Paid',
      'amount_received': 'Amount Received',
      'note_optional_hint': 'Write notes or category (Optional)',

      // Auth & Household Setup
      'login': 'Login',
      'signup': 'Sign Up',
      'email_address': 'Email Address',
      'password': 'Password',
      'full_name': 'Full Name',
      'create_account': 'Create Account',
      'dont_have_account': "Don't have an account? Sign up",
      'already_have_account': 'Already have an account? Login',
      'manage_shared_expenses': 'Manage shared expenses effortlessly',
      'setup_household': 'Setup Household / Group',
      'create_new_household': 'Create New Household',
      'join_household': 'Join Household',
      'enter_invite_code': 'Enter Invite Code',
      'edit_household_name': 'Edit Household Name',
      'or_divider': 'OR',
      'sign_in_with_google': 'Sign in with Google',
      'continue_with_google': 'Continue with Google',
      'forgot_password': 'Forgot Password?',
      'reset_password': 'Reset Password',
      'reset_password_desc': 'Enter your registered email address to receive password reset link.',
      'send_reset_link': 'Send Reset Link',
      'reset_email_sent': 'Password reset link sent to your email!',
      'confirm_password': 'Confirm Password',
      'password_min_length': 'Password must be at least 6 characters',
      'passwords_do_not_match': 'Passwords do not match',
      'recovery_key': 'Security Recovery PIN / Key',
      'recovery_key_hint': 'e.g. 1998 / 1234 / secret pin',
      'recovery_key_desc': 'Used to reset password if you forget it (works without Gmail/email access).',
      'recovery_method_key': 'Use Recovery Key / PIN',
      'recovery_method_email': 'Send Email Link',
      'enter_recovery_key': 'Enter Security Recovery Key / PIN',
      'new_password': 'New Password',
      'confirm_new_password': 'Confirm New Password',
      'password_reset_success': 'Password reset successfully! Logging you in...',
      'incorrect_recovery_key': 'Incorrect Security Recovery Key / PIN.',
      'recovery_key_settings': 'Security Recovery Key',
      'recovery_key_settings_sub': 'Set or update your secret password recovery PIN',
      'save_recovery_key': 'Save Recovery Key',
      'recovery_key_saved': 'Security Recovery Key updated successfully!',
    },
    'ta': {
      // Core Navigation & Tabs
      'app_title': 'SplitLedger',
      'home_tab': 'முகப்பு',
      'split_tab': 'பிரிப்பு',
      'history_tab': 'கணக்குகள்',
      'reports_tab': 'அறிக்கைகள்',
      'settings_tab': 'அமைப்புகள்',

      // Dashboard Header & Cards
      'wallet': 'வாலட்',
      'set_wallet': 'வாலட் தொகை அமைக்க',
      'wallet_amount': 'வாலட் தொகை',
      'wallet_balance': 'உங்கள் வாலட் இருப்பு',
      'wallet_desc': 'மொத்த பட்ஜெட் அல்லது கையிருப்புத் தொகையை உள்ளிடவும்:',
      'wallet_not_set': 'தொகையை அமைக்க அழுத்தவும்',
      'total_received': 'மொத்தம் பெற்றது',
      'total_paid': 'மொத்தம் செலுத்தியது',
      'your_balance': 'மீதி இருப்பு',
      'cash_in': 'பணம் வரவு',
      'cash_out': 'பணம் செலவு',
      'you_paid': 'நான் செலுத்தியது',
      'you_received': 'நான் பெற்றது',
      'quick_expense': '1-Tap விரைவு',
      'quick_save_expense': '⚡ விரைவு செலவை சேமி',
      'spend_cash_out': 'செலவு (பணம் வெளியீடு)',
      'receive_cash_in': 'வரவு (பணம் உள்ளீடு)',
      'settle_up': 'கணக்கு முடிக்க',
      'settlements': 'நிலுவைத் தொகைகள்',
      'no_due': 'அனைத்து கணக்கும் முடிந்தது! 🎉',
      'no_due_sub': 'நிலுவைத் தொகைகள் எதுவும் இல்லை.',
      'dues_pending': 'நிலுவைகள் உள்ளன',
      'pay_upi': 'UPI பே',
      'remind_whatsapp': 'வாட்ஸ்அப்',
      'mark_paid': 'கொடுத்துவிட்டேன்',

      // Daily Budget & Targets
      'daily_spend_target': 'தினசரி செலவு இலக்கு',
      'safe_spend_per_day': 'ஒரு நாளைக்கு செலவழிக்கலாம்',
      'days_left_in': 'நாள்கள் மீதம்',
      'over_budget': 'இந்த மாதத்திற்கான பட்ஜெட் தாண்டியது',
      'tight_budget': 'குறைந்த பட்ஜெட்: கவனமாக செலவிடுங்கள்',
      'on_track': 'சரியான செலவு விகிதம்: நன்று',
      'set_wallet_target': 'தினசரி பட்ஜெட் கணக்கிட வாலட் அமைக்கவும்',

      // Category Breakdown & Reports
      'category_breakdown': 'செலவு வகைகள்',
      'category_spending_breakdown': 'வகை வாரியான செலவுப் பட்டியல்',
      'total_group_expense': 'குழுவின் மொத்த செலவு',
      'spending_by_member': 'உறுப்பினர் வாரியான செலவு',
      'member_contributions': 'உறுப்பினர்களின் பங்களிப்பு',

      // Time Filters
      'all_time': 'எப்போதும்',
      'monthly': 'மாதாந்திரம்',
      'daily': 'தினசரி',
      'weekly': 'வாராந்திரம்',
      'yearly': 'வருடாந்திரம்',
      'pick_month': 'மாதம் தேர்ந்தெடு',

      // Search, Filter & Export
      'search_hint': 'குறிப்பு, வகை அல்லது பெயரைத் தேடுக...',
      'search_title': 'பரிவர்த்தனைகளைத் தேடுக',
      'filter_options': 'விருப்பங்கள்',
      'select_date_range': 'தேதி வரம்பைத் தேர்ந்தெடு',
      'filter_by_amount': 'தொகை வாரியாக வடிகட்டு',
      'min_amount': 'குறைந்தபட்ச தொகை (₹)',
      'max_amount': 'அதிகபட்ச தொகை (₹)',
      'apply_filter': 'வடிகட்டியைப் பயன்படுத்து',
      'clear_filter': 'நீக்கு',
      'export_csv': 'CSV / Excel ஏற்றுமதி',
      'export_pdf': 'PDF அறிக்கை',
      'share_app': 'செயலியைப் பகிர்க',

      // Settings & Appearance
      'appearance_theme': 'தோற்றம் & தீம்',
      'theme_accent_color': 'தீம் முதன்மை நிறம்',
      'theme_mode_system': 'கணினி அமைப்பு',
      'theme_mode_light': 'ஒளி பயன்முறை',
      'theme_mode_dark': 'இருண்ட பயன்முறை',
      'language': 'மொழி / Language',
      'household_settings': 'குழு அமைப்புகள்',
      'household_name': 'குழுவின் பெயர்',
      'invite_code': 'உங்கள் அழைப்புக் குறியீடு',
      'invite_code_copied': 'அழைப்புக் குறியீடு நகலெடுக்கப்பட்டது!',
      'help_support': 'உதவி & ஆதரவு',
      'privacy_mode': 'தனியுரிமை முறை (இருப்பை மறைக்க)',
      'privacy_mode_sub': 'முகப்பு கார்டுகளில் இருப்புத் தொகையை மறைக்க',
      'storage_backup_title': 'தரவு சேமிப்பு & காப்புப்பிரதி',
      'storage_mode': 'சேமிப்பு முறை',
      'storage_cloud': 'கிளவுட் ஒத்திசைவு (Firebase)',
      'storage_local': 'மொபைல் சேமிப்பு (ஆஃப்லைன்)',
      'storage_mode_desc': 'ஆன்லைன் கிளவுட் அல்லது ஆஃப்லைன் சேமிப்பு முறையைத் தேர்ந்தெடுக்கவும்.',
      'backup_export': 'தரவு காப்புப்பிரதி (JSON)',
      'backup_export_sub': 'அனைத்து பரிவர்த்தனைகளையும் கோப்பாகப் பகிர்க',
      'restore_import': 'தரவை மீட்டமைக்க (JSON)',
      'restore_import_sub': 'காப்புப்பிரதி JSON கோப்பிலிருந்து பரிவர்த்தனைகளை மீட்டெடுக்க',
      'logout': 'வெளியேறு',
      'logout_confirm': 'நிச்சயமாக வெளியேற விரும்புகிறீர்களா?',
      'leave_household': 'குழுவிலிருந்து வெளியேறு',
      'leave_household_confirm': 'இந்தக் குழுவிலிருந்து நிச்சயமாக வெளியேற விரும்புகிறீர்களா?',
      'clear_all_tx': 'அனைத்து பரிவர்த்தனைகளையும் நீக்கு',
      'clear_all_tx_confirm': 'குழுவின் அனைத்து பரிவர்த்தனைகளையும் நிச்சயமாக நீக்க விரும்புகிறீர்களா?',

      // Categories
      'currency': 'நாணயம்',
      'food': 'உணவு & ஹோட்டல்',
      'fuel': 'பெட்ரோல் & பயணம்',
      'tea': 'டீ & ஸ்நாக்ஸ்',
      'grocery': 'மளிகை பொருட்கள்',
      'rent': 'வீட்டு வாடகை',
      'bills': 'மின்சாரம் & பில்',
      'entertainment': 'பொழுதுபோக்கு',
      'shopping': 'ஷாப்பிங்',
      'medical': 'மருத்துவம் & நலம்',
      'settle': 'செட்டில்மெண்ட்',
      'other': 'மற்றவை',

      // Actions & Dialogs
      'cancel': 'ரத்து',
      'save': 'சேமி',
      'update': 'மாற்று',
      'delete': 'நீக்கு',
      'edit': 'திருத்து',
      'close': 'மூடு',
      'done': 'முடிந்தது',
      'copy': 'நகலெடு',
      'paste_clipboard': 'கிளிப்போர்டிலிருந்து ஒட்டு',
      'replace_existing': 'தற்போதுள்ளவற்றை மாற்றி அமை',
      'replace_existing_sub': 'தேர்ந்தெடுத்தால் பழைய பரிவர்த்தனைகள் அழிக்கப்படும்',
      'restore_now': 'இப்போதே மீட்டமை',
      'delete_tx_title': 'பரிவர்த்தனையை நீக்கவா?',
      'delete_tx_confirm': 'இந்த பரிவர்த்தனையை நிச்சயமாக நீக்க விரும்புகிறீர்களா?',
      'tx_deleted': 'பரிவர்த்தனை நீக்கப்பட்டது',

      // Table & List Headers
      'recent_transactions': 'சமீபத்திய பரிவர்த்தனைகள்',
      'no_transactions_yet': 'பரிவர்த்தனைகள் எதுவும் இல்லை.',
      'tap_to_add_tx': '+ பட்டனை அழுத்தி பரிவர்த்தனையை சேர்க்கவும்',
      'no_matching_tx': 'பொருந்தும் பரிவர்த்தனைகள் இல்லை.',
      'notes_category_header': 'குறிப்பு / வகை',
      'amount_header': 'தொகை',
      'by_header': 'செலுத்தியவர்',
      'you': 'நீங்கள்',
      'description': 'விவரம்',
      'category': 'பிரிவு',
      'date_time': 'தேதி & நேரம்',
      'due_date': 'கடைசி தேதி',
      'repeat': 'மீண்டும் தொடர்',
      'end_date_optional': 'முடிவு தேதி (விருப்பத்தேர்வு)',

      // Add & Edit Transaction
      'add_transaction': 'பரிவர்த்தனை சேர்க்க',
      'edit_transaction': 'பரிவர்த்தனை திருத்த',
      'who_paid': 'யார் செலுத்தினார்?',
      'who_received': 'யார் பெற்றார்?',
      'amount_paid': 'செலுத்திய தொகை',
      'amount_received': 'பெற்ற தொகை',
      'note_optional_hint': 'குறிப்பு அல்லது வகை (விருப்பத்தேர்வு)',

      // Auth & Household Setup
      'login': 'உள்நுழை',
      'signup': 'பதிவு செய்',
      'email_address': 'மின்னஞ்சல் முகவரி',
      'password': 'கடவுச்சொல்',
      'full_name': 'முழு பெயர்',
      'create_account': 'கணக்கை உருவாக்கு',
      'dont_have_account': 'கணக்கு இல்லையா? பதிவு செய்க',
      'already_have_account': 'ஏற்கனவே கணக்கு உள்ளதா? உள்நுழைக',
      'manage_shared_expenses': 'பகிர்ந்த செலவுகளை எளிதாக நிர்வகிக்கவும்',
      'setup_household': 'குடும்பம் / குழுவை அமைக்கவும்',
      'create_new_household': 'புதிய குழுவை உருவாக்கவும்',
      'join_household': 'குழுவில் இணையவும்',
      'enter_invite_code': 'அழைப்புக் குறியீட்டை உள்ளிடவும்',
      'edit_household_name': 'குழுவின் பெயரை மாற்றுக',
      'or_divider': 'அல்லது',
      'sign_in_with_google': 'Google மூலம் உள்நுழைக',
      'continue_with_google': 'Google மூலம் தொடர்க',
      'forgot_password': 'கடவுச்சொல் மறந்துவிட்டதா?',
      'reset_password': 'கடவுச்சொல்லை மீட்டமை',
      'reset_password_desc': 'கடவுச்சொல் மீட்டமைப்பு இணைப்பைப் பெற உங்கள் மின்னஞ்சலை உள்ளிடவும்.',
      'send_reset_link': 'இணைப்பு அனுப்பு',
      'reset_email_sent': 'கடவுச்சொல் மீட்டமைப்பு இணைப்பு உங்கள் மின்னஞ்சலுக்கு அனுப்பப்பட்டது!',
      'confirm_password': 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
      'password_min_length': 'கடவுச்சொல் குறைந்தது 6 எழுத்துகள் இருக்க வேண்டும்',
      'passwords_do_not_match': 'கடவுச்சொற்கள் பொருந்தவில்லை',
      'recovery_key': 'பாதுகாப்பு மீட்புக் குறியீடு (Recovery PIN / Key)',
      'recovery_key_hint': 'எ.கா. 1998 / 1234 / ரகசிய பின்',
      'recovery_key_desc': 'கடவுச்சொல்லை மறந்தால் மீட்க உதவும் (மின்னஞ்சல் அணுகல் தேவையில்லை).',
      'recovery_method_key': 'மீட்புக் குறியீடு மூலம்',
      'recovery_method_email': 'மின்னஞ்சல் இணைப்பு மூலம்',
      'enter_recovery_key': 'பாதுகாப்பு மீட்புக் குறியீட்டை உள்ளிடவும்',
      'new_password': 'புதிய கடவுச்சொல்',
      'confirm_new_password': 'புதிய கடவுச்சொல்லை உறுதிப்படுத்தவும்',
      'password_reset_success': 'கடவுச்சொல் வெற்றிகரமாக மீட்டமைக்கப்பட்டது! உள்நுழைகிறது...',
      'incorrect_recovery_key': 'தவறான பாதுகாப்பு மீட்புக் குறியீடு (Recovery Key).',
      'recovery_key_settings': 'பாதுகாப்பு மீட்புக் குறியீடு',
      'recovery_key_settings_sub': 'கடவுச்சொல் மீட்புக்கான ரகசிய பின்னை மாற்றுக',
      'save_recovery_key': 'மீட்புக் குறியீட்டை சேமி',
      'recovery_key_saved': 'பாதுகாப்பு மீட்புக் குறியீடு வெற்றிகரமாக மாற்றப்பட்டது!',
    },
  };

  static String tr(AppLanguage lang, String key) {
    final langMap = _localizedValues[lang.code] ?? _localizedValues['en']!;
    return langMap[key] ?? key;
  }
}
