import 'language_controller.dart';

class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'SplitLedger',
      'wallet': 'Wallet',
      'set_wallet': 'Set Wallet Amount',
      'total_received': 'Total Received',
      'total_paid': 'Total Paid',
      'your_balance': 'Your Balance',
      'cash_in': 'Cash In',
      'cash_out': 'Cash Out',
      'you_paid': 'You Paid',
      'you_received': 'You Received',
      'quick_expense': '1-Tap Quick',
      'settle_up': 'Settle Up',
      'settlements': 'Settlements',
      'no_due': 'All Settled Up! 🎉',
      'no_due_sub': 'No pending dues in this group.',
      'pay_upi': 'UPI Pay',
      'remind_whatsapp': 'WhatsApp',
      'mark_paid': 'Mark as Paid',
      'daily_spend_target': 'Daily Spend Target',
      'safe_spend_per_day': 'per day safe spend',
      'days_left': 'days left in',
      'category_breakdown': 'Category Breakdown',
      'all_time': 'All Time',
      'monthly': 'Monthly',
      'daily': 'Daily',
      'weekly': 'Weekly',
      'yearly': 'Yearly',
      'search_hint': 'Search notes, category, or name...',
      'filter_options': 'Options',
      'export_csv': 'Export CSV / Excel',
      'export_pdf': 'Export PDF',
      'appearance_theme': 'Appearance & Theme',
      'language': 'Language / மொழி',
      'household_settings': 'Household Settings',
      'invite_code': 'Your Invite Code',
      'help_support': 'Help & Support',
      'logout': 'Logout',
      'home_tab': 'Home',
      'split_tab': 'Split',
      'history_tab': 'Ledger',
      'reports_tab': 'Reports',
      'settings_tab': 'Settings',
      'storage_backup_title': 'Data Storage & Backup',
      'storage_mode': 'Storage Mode',
      'storage_cloud': 'Cloud Sync (Firebase)',
      'storage_local': 'Device Only (Offline)',
      'storage_mode_desc': 'Switch between real-time cloud sync and private offline local storage.',
      'backup_export': 'Backup Data (JSON)',
      'backup_export_sub': 'Download or share all transactions and balances',
      'restore_import': 'Restore Data (JSON)',
      'restore_import_sub': 'Import transactions from a JSON backup file or text',
      'privacy_mode': 'Privacy Mode (Hide Balances)',
      'privacy_mode_sub': 'Mask sensitive balance numbers on cards with dots',
      'currency': 'Currency',
      'food': 'Food & Dining',
      'fuel': 'Fuel & Travel',
      'tea': 'Tea & Snacks',
      'grocery': 'Groceries',
      'rent': 'Rent & House',
      'bills': 'Utilities & Bills',
      'entertainment': 'Fun & Movies',
      'shopping': 'Shopping',
      'other': 'Others',
    },
    'ta': {
      'app_title': 'SplitLedger',
      'wallet': 'வாலட்',
      'set_wallet': 'வாலட் தொகை அமைக்க',
      'total_received': 'மொத்தம் பெற்றது',
      'total_paid': 'மொத்தம் செலுத்தியது',
      'your_balance': 'மீதி இருப்பு',
      'cash_in': 'பணம் வரவு',
      'cash_out': 'பணம் செலவு',
      'you_paid': 'நான் செலுத்தியது',
      'you_received': 'நான் பெற்றது',
      'quick_expense': '1-Tap விரைவு',
      'settle_up': 'கணக்கு முடிக்க',
      'settlements': 'செட்டில்மெண்ட்',
      'no_due': 'அனைத்து கணக்கும் முடிந்தது! 🎉',
      'no_due_sub': 'நிலுவைத் தொகைகள் எதுவும் இல்லை.',
      'pay_upi': 'UPI பே',
      'remind_whatsapp': 'வாட்ஸ்அப்',
      'mark_paid': 'கொடுத்துவிட்டேன்',
      'daily_spend_target': 'தினசரி செலவு இலக்கு',
      'safe_spend_per_day': 'ஒரு நாளைக்கு செலவழிக்கலாம்',
      'days_left': 'நாள்கள் மீதம்',
      'category_breakdown': 'செலவு வகைகள்',
      'all_time': 'எப்போதும்',
      'monthly': 'மாதாந்திரம்',
      'daily': 'தினசரி',
      'weekly': 'வாராந்திரம்',
      'yearly': 'வருடாந்திரம்',
      'search_hint': 'குறிப்பு அல்லது பெயரைத் தேடுக...',
      'filter_options': 'விருப்பங்கள்',
      'export_csv': 'CSV / Excel ஏற்றுமதி',
      'export_pdf': 'PDF அறிக்கை',
      'appearance_theme': 'தோற்றம் & தீம்',
      'language': 'மொழி / Language',
      'household_settings': 'குழு அமைப்புகள்',
      'invite_code': 'உங்கள் அழைப்புக் குறியீடு',
      'help_support': 'உதவி & ஆதரவு',
      'logout': 'வெளியேறு',
      'home_tab': 'முகப்பு',
      'split_tab': 'பிரிப்பு',
      'history_tab': 'கணக்குகள்',
      'reports_tab': 'அறிக்கைகள்',
      'settings_tab': 'அமைப்புகள்',
      'storage_backup_title': 'தரவு சேமிப்பு & காப்புப்பிரதி',
      'storage_mode': 'சேமிப்பு முறை',
      'storage_cloud': 'கிளவுட் ஒத்திசைவு (Firebase)',
      'storage_local': 'மொபைல் சேமிப்பு (ஆஃப்லைன்)',
      'storage_mode_desc': 'ஆன்லைன் கிளவுட் அல்லது ஆஃப்லைன் சேமிப்பு முறையைத் தேர்ந்தெடுக்கவும்.',
      'backup_export': 'தரவு காப்புப்பிரதி (JSON)',
      'backup_export_sub': 'அனைத்து பரிவர்த்தனைகளையும் கோப்பாகப் பகிர்க',
      'restore_import': 'தரவை மீட்டமைக்க (JSON)',
      'restore_import_sub': 'காப்புப்பிரதி JSON கோப்பிலிருந்து பரிவர்த்தனைகளை மீட்டெடுக்க',
      'privacy_mode': 'தனியுரிமை முறை (இருப்பை மறைக்க)',
      'privacy_mode_sub': 'முகப்பு கார்டுகளில் இருப்புத் தொகையை மறைக்க',
      'currency': 'நாணயம்',
      'food': 'உணவு & ஹோட்டல்',
      'fuel': 'பெட்ரோல் & பயணம்',
      'tea': 'டீ & ஸ்நாக்ஸ்',
      'grocery': 'மளிகை பொருட்கள்',
      'rent': 'வீட்டு வாடகை',
      'bills': 'மின்சாரம் & பில்',
      'entertainment': 'பொழுதுபோக்கு',
      'shopping': 'ஷாப்பிங்',
      'other': 'மற்றவை',
    },
  };

  static String tr(AppLanguage lang, String key) {
    final langMap = _localizedValues[lang.code] ?? _localizedValues['en']!;
    return langMap[key] ?? key;
  }
}

